apiVersion: v1
kind: Service
metadata:
  name: observability-platform
  namespace: observability
  labels:
    app.kubernetes.io/name: observability-platform
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: observability-platform
  ports:
    - name: http
      port: 8000
      targetPort: http
      protocol: TCP
